version: "3.8"

services:
  # Service with application container
  film-library:
    image: film-library/web-backend
    depends_on:
      postgres-database:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "8000:8000"

  # Service with postgres database container
  postgres-database:
    image: postgres:latest
    volumes:
      - postgres-database:/data/db/postgres
    environment:
      - POSTGRES_DB=film_library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service for managing postgres migrations
  postgres-migrations:
    image: migrate/migrate
    depends_on:
      postgres-database:
        condition: service_healthy
    volumes:
      - ../../migrations/postgres:/data/db/postgres/migrations
    command:
      [ "-path", "/data/db/postgres/migrations", "-database", "postgres://postgres:admin@postgres-database:5432/film_library?sslmode=disable", "up" ]

volumes:
  postgres-database:
